### ISSUE TITLE
iOS openDocument not working in 0.10.x

### ISSUE THREAD

**Issue by camloken** [wkh237/react-native-fetch-blob#195]
I noticed this issue was brought up before, but for some reason in release 0.10.+ using the RNFetchBlob.ios.openDocument() function is still not working. Here is the code:
```javascript
handleDownload() {
    const attachmentUrl = [ChatStore.getBaseUrl(), 'attachments/', this.props.attachment.id, '/ORIGINAL?token=', AuthorizationStore.getAttachmentToken()].join('');
    RNFetchBlob
    .config({
      fileCache: true,
      addAndroidDownloads: {
        useDownloadManager: true,
        notification: true,
        mime: this.props.attachment.mimeType,
        mediaScannable: true,
      },
    })
    .fetch('GET', attachmentUrl, {
      Authorization: AuthorizationStore.getAuthHeaderValue(),
    })
    .then((res) => {
      if (Platform.OS === 'ios') {
        RNFetchBlob.ios.openDocument(res.path());
      }
    });
  }
```

This has been tested on an iPhone 6s with no results.
I get the following warning in react native:

RNFetchBlob.openDocument() is not a function

**Should the reference be to ios:**

RNFetchBlob.ios.openDocument()

<img src="https://cloud.githubusercontent.com/assets/2279954/20610552/912a73ce-b258-11e6-8bde-6fd779baccce.png" width="400" />

**Comment by camloken** [comment]
It seems iOS needs an extension on the end of the path, otherwise openDocument( ) won't work: 

e.g. RNFetchBlob.ios.openDocument(path/to/file.ext);

You can append the extension type in the .config method:
```javascript
    RNFetchBlob
    .config({
      fileCache: true,
      appendExt: 'jpg', 
    })
    .fetch('GET', attachmentUrl, {
      Authorization: AuthorizationStore.getAuthHeaderValue(),
    })
    .then((res) => {
      if (Platform.OS === 'ios') {
        RNFetchBlob.ios.openDocument(res.path()); // results in path/to/file.jpg
      }
    });
```

RNFetchBlob.ios.openDocument( )  and RNFetchBlob.ios.previewDocument( ) currently behave the opposite of what you would expect. Hope that gets fixed.
