### ISSUE TITLE
Issue running react-native-fetch-blob on 0.9.2.beta.2

### ISSUE THREAD

**Issue by shilpan** [wkh237/react-native-fetch-blob#93]
react-native build fails with the following stack-trace:

```
react-native-fetch-blob/android/src/main/java/com/RNFetchBlob/RNFetchBlobReq.java:454: error: cannot find symbol
        resp.close();
            ^
  symbol:   method close()
  location: variable resp of type Response
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:react-native-fetch-blob:compileReleaseJavaWithJavac FAILED
```

**Comment by wkh237** [comment]
@shilpan , if your project RN version < 0.31, just remove that line and it will work again. This is an issue due to `0.9.2-beta.2` prelink script change.

**Comment by wkh237** [comment]
Reference #90

**Comment by shilpan** [comment]
interesting. I would love to use 0.31 but firebase android doesn't seem to work on 0.31 :/

**Comment by wkh237** [comment]
I've observed the same issue issue, on 0.31 Android module  does not work in Debug Mode.

**Comment by wkh237** [comment]
Here's an example, the following code does not work in Android `Debug Mode`, XMLHttpRequest not even got called.

```js
firebase.initializeApp(config)

describe('firebase login', (report, done) => {

  firebase.auth().signInWithEmailAndPassword('xeiyan@gmail.com', 'rnfbtest1024')
    .catch((err) => {
      console.log('firebase sigin failed', err)
    })

  firebase.auth().onAuthStateChanged((user) => {
    report(<Assert key="login status" uid="100"
      expect={true}
      actual={user !== null}/>,
    <Info key="user content" uid="user data">
      <Text>{JSON.stringify(user)}</Text>
    </Info>)
    done()
  })
})
```

However, if I move the `  firebase.initializeApp(config)` line into the same scope it works

```diff
- firebase.initializeApp(config)                                                                                                                         

describe('firebase login', (report, done) => {
+ firebase.initializeApp(config)                                                                                                                            
  firebase.auth().signInWithEmailAndPassword('xeiyan@gmail.com', 'rnfbtest1024')
    .catch((err) => {
      console.log('firebase sigin failed', err)
    })

  firebase.auth().onAuthStateChanged((user) => {
    report(<Assert key="login status" uid="100"
      expect={true}
      actual={user !== null}/>,
    <Info key="user content" uid="user data">
      <Text>{JSON.stringify(user)}</Text>
    </Info>)
    done()
  })
})
```

**Comment by shilpan** [comment]
that is so weird. But that resolves it, thanks!

**Comment by wkh237** [comment]
reference https://github.com/davideast/firebase-react-native-sample/issues/14

**Comment by wkh237** [comment]
@shilpan , I've published `0.9.2-beta.3` which should fixed this issue 😄

**Comment by shilpan** [comment]
It does fix the issue. Thanks!

**Comment by wkh237** [comment]
Okay, let's close this issue :)
